### ISSUE TITLE
CNAME alias crashes record_sets generator

### ISSUE THREAD

**Issue by JariInc** [gtaylor/python-route53#8]
```python
aws_conn = route53.connect(
    aws_access_key_id="foo",
    aws_secret_access_key="bar,
)
zone = aws_conn.get_hosted_zone_by_id("zoneid")
for rec in zone.record_sets:
    print(rec)
```
This crashes if the zone contains CNAME Alias
```
<AResourceRecordSet: domain.fi.>
<NSResourceRecordSet: domain.fi.>
<SOAResourceRecordSet: domain.fi.>
<CNAMEResourceRecordSet: admin.domain.fi.>
Traceback (most recent call last):
  File "bin/dyndns", line 4, in <module>
    import tooltip.dyndns
  File "/share/private/jari/fb-local/tooltip/dyndns.py", line 34, in <module>
    for rec in zone.record_sets:
  File "/share/private/jari/fb-local/ENV/lib/python3.4/site-packages/route53/hosted_zone.py", line 84, in record_sets
    for rrset in self.connection._list_resource_record_sets_by_zone_id(self.id):
  File "/share/private/jari/fb-local/ENV/lib/python3.4/site-packages/route53/connection.py", line 90, in _do_autopaginating_api_call
    for record in parser_func(root, connection=self, **parser_kwargs):
  File "/share/private/jari/fb-local/ENV/lib/python3.4/site-packages/route53/xml_parsers/list_resource_record_sets_by_zone_id.py", line 140, in list_resource_record_sets_by_zone_id_parser
    yield parse_rrset(e_rrset, connection, zone_id)
  File "/share/private/jari/fb-local/ENV/lib/python3.4/site-packages/route53/xml_parsers/list_resource_record_sets_by_zone_id.py", line 117, in parse_rrset
    return RRSetSubclass(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'alias_dns_name'
```
If I go and change the CNAME alias to regular CNAME, for example, it works just fine.

**Comment by gtaylor** [comment]
Fixed by #11.
